# Makefile for the IDAI-780 Capstone Project
preprocess:
	python preprocess.py

train:
	python train.py

evaluate:
	python evaluate.py

pipeline:
	preprocess train evaluate
	@echo "Pipeline completed successfully!"